### ISSUE TITLE
mkdoc fails in CI

### ISSUE THREAD

**Issue by Lee-W** [Woile/commitizen#119] opened 2020-01-13 15:15 UTC
**Goal**
fix making documment issue
e.g., [Upload Python Package - on: push (2a2c1cc)](https://github.com/Woile/commitizen/commit/2a2c1ccb53508f70ac75dc102bb8dbf2e7c20173/checks?check_suite_id=395301498)

**Description**
It seems `GITHUB_ACTOR` and `GITHUB_TOKEN` are not given. If exposing of these data  is the concern, maybe we can try [actions-gh-page](https://github.com/peaceiris/actions-gh-pages)
?

**Comment by Woile** [comment] 2020-01-14 09:14
Nice, I like the github actions page.
I think that the problem is [here](https://github.com/Woile/commitizen/blob/master/scripts/publish#L9), since my last update from `actions/checkout@v1` to `actions/checkout@v2` this has somehow broken. I've been updating the docs manually.

**Comment by Woile** [comment] 2020-01-21 14:42
@Lee-W can we close this one?

**Comment by Lee-W** [comment] 2020-01-21 14:43
Yes 🙂

**Closed** 2020-01-21 14:44 UTC
Labels: help wanted
